### ISSUE TITLE
Should we set `{ server: true}`?

### ISSUE THREAD

**Issue by christianbundy** [ssbc/ssb-config#36]
Currently ssb-server has a [bug](https://github.com/ssbc/ssb-server/issues/577) and while we have a workaround we still have no idea why the workaround is necessary (see https://github.com/ssbc/multiserver/issues/33). In the same vein as https://github.com/ssbc/ssb-config/issues/35, I'm wondering whether we should merge the workaround into ssb-config until we can get documentation or a bugfix upstream.

cc: @dominictarr @arj03 @regular 

See also: `%cM+EpikjtEqpkJMhuSvTwgmr6isAw3FKhTzNSEa9EyQ=.sha256`

**Comment by arj03** [comment]
Closed by multiserver 3.3.0
