### ISSUE TITLE
Listening on false

### ISSUE THREAD

**Issue by christianbundy** [ssbc/ssb-config#43]
It looks like something changed recently in a not-so-backward-compatible way. See: https://github.com/ssbc/ssb-ooo/pull/3

I'm wondering whether this might have been caused by https://github.com/ssbc/ssb-config/pull/31?

I don't personally mind the change, but I think it snuck in as a minor/patch bump rather than a major version. Could that be right?

## Used to work

```js
createSbot({
  port: 34597,
  keys: ssbKeys.generate()
})
```

## Now required

```js
createSbot({
  host: 'localhost',
  port: 34597,
  keys: ssbKeys.generate()
})
```

cc: @mixmix @dominictarr

**Comment by christianbundy** [comment]
I'm unable to reproduce now -- closing.

**Comment by dominictarr** [comment]
if you pass false as the address to a server it should default to '::' or '0.0.0.0' i think
