### ISSUE TITLE
rename to sbot-config?

### ISSUE THREAD

**Issue by pfraze** [ssbc/ssb-config#5]
`ssb-config` is a little confusing, I think, this is config for sbot

**Comment by dominictarr** [comment]
sure but if we rename this what other things do we need to rename too?

**Comment by pfraze** [comment]
I think just phoenix, it's `ssbplug-phoenix`, maybe change that to `sbot-phoenix` (do we need `plug`?)

**Comment by dominictarr** [comment]
@pfraze yeah, ssbplug feels strange, we didn't end up changing that.

hmm, I'm not sure if we should rename this, there are several things that use this not just sbot
https://www.npmjs.com/browse/depended/ssb-config

**Comment by pfraze** [comment]
hmmmm are you concerned about the bugs introduced? i can justify it semantically by saying those deps are using sbot, not ssb, but it's splitting hairs and I'd be fine dropping the issue either way

**Comment by dominictarr** [comment]
no, I just feel it wouldn't really be worth it. the ssb- means it's all related to ssb. If we where to adopt more precise subprefixes it should mark a strong distinction... otherwise you'd have to try and remember is <x> ssb-<x> or sbot-<x>?

**Comment by pfraze** [comment]
ok
