### ISSUE TITLE
undocumented caps.shs and caps.sign

### ISSUE THREAD

**Issue by ahdinosaur** [ssbc/ssb-config#50]
best explanation i've found is from @clehner: [%9yC1XNJJtNiJVCMGchCO7iRKB6xMUrDaCfLUeFPTk3o=.sha256](https://viewer.scuttlebot.io/%259yC1XNJJtNiJVCMGchCO7iRKB6xMUrDaCfLUeFPTk3o%3D.sha256)

**Comment by dominictarr** [comment]
example config:

generate random values in node repl

``` js
randomValue = require('crypto').randomBytes(32).toString('base64')
```

then copy them into ~/.ssb/config
```
"caps": {
  "sign": randomValue1,
  "shs": randomValue2
}
```

/cc @frankiebee

**Comment by ygrek** [comment]
I am confused, which one is network key? And what is the second one? There seems to be only one secret key in the protocol-guide..

**Comment by ygrek** [comment]
hm, looking at https://github.com/ssbc/ssb-config/blob/master/defaults.js#L53 `sign` is null and `shs` is the network key

**Comment by staltz** [comment]
See also https://github.com/ssbc/ssb-caps
